import { titleformat } from "./components/Header"
export default function head({params}:{params:{slug:string}}) {
    return (
        <>
          <title>{titleformat(params.slug)}</title>
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </>
      )
}
